config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :websites, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'websites#angular'
  get 'website/:id', to: 'websites#show', as: 'website_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'food-news', to: 'pages#food_news'

  resources :blogs do 
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/models/website.rb
class Website < ApplicationRecord
	has_many :partners
	accepts_nested_attributes_for :partners,
																allow_destroy: true,
																reject_if: lambda { |attrs| attrs['name'].blank? }

	validates_presence_of :title, :body

	mount_uploader :thumb_image, WebsiteUploader
	mount_uploader :main_image, WebsiteUploader

	def self.angular
		where(subtitle: 'Angular')
	end

	def self.by_position
		order("position ASC")
	end

	scope :ruby_on_rails_website_items, -> { where(subtitle: 'Ruby on Rails') }
end

# def set_defaults
#		if self.main_image == nil
#			self.main_image = "http://placehold.it/600x400"
# end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website_item, only: [:edit, :update, :show, :destroy]
  layout 'website'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  
	def index
		@website_items = Website.by_position
	end

  def sort
    params[:order].each do |key, value|
      Website.find(value[:id]).update(position: value[:position])
  end

    render nothing: true
  end

  def angular
    @angular_website_items = Website.angular
  end

	def new
		@website_item = Website.new
	end

	def create
    @website_item = Website.new(website_params)

    respond_to do |format|
      if @website_item.save
        format.html { redirect_to websites_path, notice: 'Your website item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @website_item.update(website_params)
        format.html { redirect_to websites_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy

  	# Destroy/delete the record
  	@website_item.destroy

  	# Redirect
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Record was removed.' }
    end
  end

  private

  def website_params
    params.require(:website).permit(:title, 
                                    :subtitle, 
                                    :body,
                                    :main_image,
                                    :thumb_image,
                                    partners_attributes: [:id, :name, :_destroy]
                                    )
  end

  def set_website_item
    @website_item = Website.find(params[:id])
  end
end

app/helpers/websites_helper.rb
module WebsitesHelper
	def image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
	end

	def website_img img, type
		if img.model.main_image? || img.model.thumb_image?
			img
		elsif type == 'thumb'
			image_generator(height: '350', width: '200')
		else type == 'main'
			image_generator(height: '600', width: '400')
		end
	end
end

app/views/websites/_form.html.erb
<%= form_for(@website_item) do |f| %>
  <% if @website_item.errors.any? %>
    <% @website_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
        </div>

        <div class="form-group">
          <label class="btn btn-primary">
            Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
          </label>
        </div>

        <div class="form-group">
          <label class="btn btn-primary">
            Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
          </label>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: 13 %>
        </div>
      </div>
    </div>

  <hr>

  <div class="col-md-12">
    <h2>Partners Include:</h2>
    <div>
      <%= f.fields_for :partners do |partner_form| %>
        <%= render 'partner_fields', f: partner_form %>
      <% end %>

      <div>
        <%= link_to_add_association 'Add Partner', f, :partners %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Event', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/websites/_partner_fields.html.erb
<div class="form-group nested-fields">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form_control' %>
	<%= link_to_remove_association 'Remove Partner', f %>
</div>

app/views/websites/_website_item.html.erb
<div class="col-md-4">
	<div class="card" data-id="<%= website_item.id %>">
	  <%= image_tag website_img(website_item.thumb_image, 'thumb'), width: '100%' %>
	  <p class="card-text">
	  	<span><%= link_to website_item.title, website_show_path(website_item) %></span> <%= website_item.subtitle %>
	  </p>
	</div>
</div>

app/views/websites/angular.html.erb
<h1>Event Items</h1>

<%= link_to "Create New Item", new_website_url if logged_in?(:site_admin)%>

<% @angular_website_items.each do |website_item| %>
	<p><%= link_to website_item.title, website_show_path(website_item) %></p>
	<p><%= website_item.subtitle %></p>
	<p><%= website_item.body %></p>
	<%= image_tag website_item.thumb_image unless website_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_website_path(website_item) if logged_in?(:site_admin) %>
	<%= link_to 'Delete Website Item', website_path(website_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/websites/edit.html.erb
<div class="container website-container">
	<h1>Modify this Event</h1>

	<%= render 'form', website_item: @website_item %>
</div>

app/views/websites/index.html.erb
<div class="album text-muted">
  <div class="container">
  	<%= source_helper("alert alert-warning") %>

    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
			<%= render partial: 'website_item', collection: @website_items %>
		</div>
	</div>
</div>

app/views/websites/new.html.erb
<div class="container website-container">
	<h1>Create a new Event Item</h1>

	<%= render 'form', website_item: @website_item %>
</div>

app/views/websites/show.html.erb
<div class="container website-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag website_img(@website_item.main_image, 'main'), width: '100%' %>
    </div>

    <div class="col-md-5">
      <h1><%= @website_item.title %></h1>

      <hr>

      <em><%= @website_item.subtitle %></em>

      <p><%= @website_item.body %></p>

      <hr>

      <h3>Partners Include:</h3>

      <% @website_item.partners.each do |p| %>
      <p><%= p.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div class="">
          <%= link_to "Edit Item", edit_website_path(@website_item), class: 'btn btn-warning' %>
        </div>
      <% end %>
    <div>
  </div>
</div>